# Stage 1: Build the React app
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .


# Set environment variables
ENV REACT_APP_BACKEND_HTTP=${REACT_APP_BACKEND_HTTP}
ENV REACT_APP_BACKEND_WS=${REACT_APP_BACKEND_WS}

CMD ["npm", "start"]

