# Stage 1: Build the React app
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .


# Set environment variables
ENV REACT_APP_BACKEND_HTTP=${REACT_APP_BACKEND_HTTP}
ENV REACT_APP_BACKEND_WS=${REACT_APP_BACKEND_WS}
# docker run -d -e REACT_APP_BACKEND_HTTP=http://localhost:4000 -e REACT_APP_BACKEND_WS=ws://localhost:4000/graphql -p 3000:3000 --name les-chat-client b00977003/les-chat-client

# ENV REACT_APP_BACKEND_HTTP=http://localhost:4000
# ENV REACT_APP_BACKEND_WS=ws://localhost:4000/graphql
# RUN npm start
CMD ["npm", "start"]

