# Stage 1: Build the React app
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json
COPY package.json ./

# Install dependencies
RUN npm install -g sequelize-cli
RUN npm install
RUN npm update

# Copy the rest of the application code
COPY . .


# Set environment variables

ENV PORT=${PORT}
ENV JWT_SECRET = ${JWT_SECRET}
ENV NODE_ENV = ${NODE_ENV}
ENV DATABASE_USERNAME=${DATABASE_USERNAME}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV DATABASE_NAME=${DATABASE_NAME}
ENV DATABASE_HOST=${DATABASE_HOST}

# RUN npm start


CMD ["sh", "-c", "npx sequelize db:migrate && npm start"]
